#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 28 22:38:30 EEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=13
shaderPack=ComplementaryUnbound_r5.9.3 + EuphoriaPatches_1.10.5
